In [1]:
import numpy as np

In [2]:
#Task1
def function1():
    x = np.arange(1,13).reshape((6,2))
    return x

In [27]:
#Task2
def function2():
    #create 3D array (3,3,3)
    #must data type should have float64
    #array value should be satart from 10 and end with 36 (both included)
    # Hint: dtype, reshape 
    
    x = np.arange(1,28,dtype=np.float64).reshape((3,3,3))+9     #wrtie your code here
    

    return x

In [47]:
#Task3
def function3():
    #extract those numbers from given array. those are must exist in 5,7 Table
    #example [35,70,105,..]
    a = np.arange(1, 100*10+1).reshape((100,10))
    x = np.r_[a[np.mod(a,5)==0],a[np.mod(a,7)==0]] #wrtie your code here
    
    y= a[np.where((np.mod(a,5)==0)&(np.mod(a,7)==0))]#x.sort() .argsort()
    return y

In [46]:
function3()

array([   5,   10,   15,   20,   25,   30,   35,   40,   45,   50,   55,
         60,   65,   70,   75,   80,   85,   90,   95,  100,  105,  110,
        115,  120,  125,  130,  135,  140,  145,  150,  155,  160,  165,
        170,  175,  180,  185,  190,  195,  200,  205,  210,  215,  220,
        225,  230,  235,  240,  245,  250,  255,  260,  265,  270,  275,
        280,  285,  290,  295,  300,  305,  310,  315,  320,  325,  330,
        335,  340,  345,  350,  355,  360,  365,  370,  375,  380,  385,
        390,  395,  400,  405,  410,  415,  420,  425,  430,  435,  440,
        445,  450,  455,  460,  465,  470,  475,  480,  485,  490,  495,
        500,  505,  510,  515,  520,  525,  530,  535,  540,  545,  550,
        555,  560,  565,  570,  575,  580,  585,  590,  595,  600,  605,
        610,  615,  620,  625,  630,  635,  640,  645,  650,  655,  660,
        665,  670,  675,  680,  685,  690,  695,  700,  705,  710,  715,
        720,  725,  730,  735,  740,  745,  750,  7

In [5]:
#Task4
def function4():
    #Swap columns 1 and 2 in the array arr.
   
    arr = np.arange(9).reshape(3,3)
    arr

  
    return arr[:,[1,0,2]] #wrtie your code here

In [6]:
#Task5
def function5():
    #Create a null vector of size 20 with 4 rows and 5 columns with numpy function
   
    z = np.zeros(20).reshape(4,5)#wrtie your code here
  
    return z

In [51]:
#Task6
def function6():
    # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively
    arr = np.zeros(10); #wrtie your code here
    arr [5]=10 
    arr [8]=20
  
    return arr

In [54]:
arr = np.zeros(10);print(arr)
arr.size

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


10

In [52]:
function6()

array([ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0., 20.,  0.])

In [8]:
#Task7
def function7():
    #  Create an array of zeros with the same shape and type as X. Dont use reshape method
    x = np.arange(4, dtype=np.int64)
  
    return np.zeros_like(x)#write your code here


In [9]:
#Task8
def function8():
    # Create a new array of 2x5 uints, filled with 6.

    x = np.full((2, 5),6,dtype=np.uint32) #write your code here
  
    return x

In [10]:
#Task9
def function9():
    # Create an array of 2, 4, 6, 8, ..., 100.
    
    a = np.arange(1,51,dtype=np.int64)*2 # write your code here
  
    return a

In [11]:
#Task10
def function10():
    # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.
    
    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt = arr-brr
  
    return subt


In [12]:
#Task11
def function11():
    # Replace all odd numbers in arr with -1 without changing arr.
    
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    ans = np.where(np.mod(arr,2)>0,-1,arr)
  
    return ans

In [13]:
#Tas12
def function12():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    
    arr = np.array([1,2,3])
    ans = np.hstack(  (np.full_like(arr,1), np.full_like(arr,2), np.full_like(arr,3), arr[:],arr[:],arr[:] )   ) 
   
    return ans

In [14]:
#Task13
def function13():
    # Set a condition which gets all items between 5 and 10 from arr.
    
    
    arr = np.array([2, 6, 1, 9, 10, 3, 27])
    ans = arr[(arr>5)&(arr<10)] 
    arr = np.arange(10, 34, 1) #write reshape code
    return ans

In [15]:
#Task14
def function14():
    # Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
    # Hint use split method
    
    
    arr = np.arange(10, 34, 1).reshape(8,3) #write reshape code
    ans = np.split(arr,4)#write your code here 
  
    return ans

In [16]:
#Task15
def function15():
    #Sort following NumPy array by the second column
    
    
    arr = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])
    ans = mat[np.sort(mat[:,1]).argsort()]
  
    return ans


In [17]:
#Task16
def function16():
    #Write a NumPy program to join a sequence of arrays along depth.
    
    
    x = np.array([[1], [2], [3]])
    y = np.array([[2], [3], [4]])
    ans = np.array(np.hsplit(np.hstack ((x,y)),1)) 
  
    return ans

In [43]:
#Task17
def function17():
    # replace numbers with "YES" if it divided by 3 and 5
    # otherwise it will be replaced with "NO"
    # Hint: np.where
    arr = np.arange(1,10*10+1).reshape((10,10))
    return           np.where((np.mod(arr,3)==0)&(np.mod(arr,5)==0),"YES","NO")# Write Your Code HERE

In [44]:
function17()

array([['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']],
      dtype='<U3')

In [19]:
#Task18
def function18():
    # count values of "students" are exist in "piaic"
    piaic = np.arange(100)
    students = np.array([5,20,50,200,301,7001])
    x = (s[np.where(s<=len(p))]).size # Write you code Here
    return x

In [20]:
#Task19
def function19():
    #Create variable "X" from 1,25 (both are included) range values
    #Convert "X" variable dimension into 5 rows and 5 columns
    #Create one more variable "W" copy of "X" 
    #Swap "W" row and column axis (like transpose)
    # then create variable "b" with value equal to 5
    # Now return output as "(X*W)+b:

    X =   np.arange(1,26).reshape(5,5) # Write your code here
    W =   X.copy().T # Write your code here 
    b =   5 # Write your code here
    output =    (X*W)+b # Write your code here
    return output

In [21]:
#Task20
def function20():
    #apply fuction "abc" on each value of Array "X"
    x = np.arange(1,11)
    def abc(x):
        return x*2+3-2

    return abc(x) #Write your Code here